<?php

$plugin = array(
  'title' => t('Variable 1-2-1-2-4'),
  'icon' => 'variable_1_2_1_2_4.png',
  'category' => t('Grid ready'),
  'theme' => 'variable_1_2_1_2_4',
  'css' => 'variable_1_2_1_2_4.admin.css',
  'regions' => array(
    'variable_1'    => t('Top (Conditional)'),
    'variable_1_2_left'  => t('Left'),
    'variable_1_2_right'  => t('Right'),
    'variable_1_2_1'  => t('Middle (Conditional)'),
    'variable_1_2_1_2_left'  => t('Left'),
    'variable_1_2_1_2_right'  => t('Right'),
    'variable_1_2_1_2_4_left'  => t('Left 16.6%'),
    'variable_1_2_1_2_4_middle'  => t('Middle 16.6%'),
    'variable_1_2_1_2_4_middle2' => t('Right 16.6%'),
    'variable_1_2_1_2_4_right' => t('Right 50%'),
  ),
);
