<?php

$plugin = array(
  'title' => t('One by 6-1-2-1'),
  'icon' => 'one_6_1_2_1.png',
  'category' => t('Grid ready'),
  'theme' => 'one_6_1_2_1',
  'css' => 'one_6_1_2_1.admin.css',
  'regions' => array(
    'one_6_1_2_1_top'    => t('Top (Conditional)'),
    'one_6_1_2_1_first'  => t('1'),
    'one_6_1_2_1_second'  => t('2'),
    'one_6_1_2_1_third'  => t('3'),
    'one_6_1_2_1_fourth'  => t('4'),
    'one_6_1_2_1_five'  => t('5'),
    'one_6_1_2_1_six'  => t('6'),
    'one_6_1_2_1_middle' => t('Middle (Conditional)'),
    'one_6_1_2_1_left'  => t('Left'),
    'one_6_1_2_1_right' => t('Right'),
    'one_6_1_2_1_bottom' => t('Bottom (Conditional)'),
  ),
);
