<?php

$plugin = array(
  'title' => t('Variable 1-2-4-6-1-2-1'),
  'icon' => 'var_1_2_4_6_1_2_1.png',
  'category' => t('Grid ready'),
  'theme' => 'var_1_2_4_6_1_2_1',
  'css' => 'var_1_2_4_6_1_2_1.admin.css',
  'regions' => array(
    'var_1'    => t('Top (Conditional)'),
    'var_1_2_first'  => t('Left'),
    'var_1_2_second'  => t('Right'),
    'var_1_2_4_first'  => t('1'),
    'var_1_2_4_second'  => t('2'),
    'var_1_2_4_third'  => t('3'),
    'var_1_2_4_fourth'  => t('4'),
    'var_1_2_4_6_first' => t('1'),
    'var_1_2_4_6_second' => t('2'),
    'var_1_2_4_6_third' => t('3'),
    'var_1_2_4_6_fourth' => t('4'),
    'var_1_2_4_6_fifth' => t('5'),
    'var_1_2_4_6_sixth' => t('6'),
    'var_1_2_4_6_1'  => t('Middle (Conditional)'),
    'var_1_2_4_6_1_2_first'  => t('Left'),
    'var_1_2_4_6_1_2_second' => t('Right'),
    'var_1_2_4_6_1_2_1' => t('Bottom (Conditional)'),
  ),
);
